const app = document.querySelector('#app');

const markets = [
  {id:'david-goliath',type:'multi',category:'History',sub:'1 Samuel',reference:'1 Samuel 17:38–51',title:'Will David defeat Goliath?',volume:'82K',thumb:'david',outcomes:[['David wins',.83],['Goliath wins',.17]],rule:'Resolves from 1 Samuel 17:50–51.',scores:[['13','12'],['5','11']]},
  {id:'lazarus',type:'live',category:'Gospels',sub:'John',reference:'John 11:43–44',title:'What happens next: Lazarus comes out?',volume:'19K',thumb:'lazarus',outcomes:[['Up',.51],['Down',.49]],rule:'Resolves from John 11:43–44.'},
  {id:'thomas',type:'multi',category:'Gospels',sub:'John',reference:'John 20:24–29',title:'Will Thomas believe before seeing Jesus?',volume:'18K',thumb:'tomb',outcomes:[['No',.78],['Yes',.22]],rule:'Resolves from John 20:24–29.'},
  {id:'jericho',type:'matchup',category:'History',sub:'Joshua',reference:'Joshua 6:20',title:'Israel — Jericho',volume:'514K',thumb:'walls',outcomes:[['Israel',.82],['Jericho',.18]],teams:[['Israel',1,.82],['Jericho',0,.18]],stage:'STORY 2',rule:'Resolves from Joshua 6:20.'},
  {id:'samson',type:'matchup',category:'History',sub:'Judges',reference:'Judges 16:28–30',title:'Samson — Philistines',volume:'300K',thumb:'samson',outcomes:[['Samson',.87],['Philistines',.13]],teams:[['Samson',1,.87],['Philistines',0,.13]],stage:'STORY 2',rule:'Resolves from Judges 16:28–30.'},
  {id:'paul-rome',type:'multi',category:'Acts',sub:'Paul',reference:'Acts 28:14–16',title:'Will Paul eventually reach Rome?',volume:'726K',thumb:'paul',outcomes:[['Yes',.99],['No',.01]],rule:'Resolves from Acts 28:14–16.'},
  {id:'abraham',type:'binary',category:'Torah',sub:'Genesis',reference:'Genesis 22:9–13',title:'Will Abraham ultimately sacrifice Isaac?',volume:'1.8M',thumb:'mountain',outcomes:[['Yes',.14],['No',.86]],rule:'Resolves from Genesis 22:9–13.'},
  {id:'red-sea',type:'binary',category:'Torah',sub:'Exodus',reference:'Exodus 14:21–22',title:'Will the Red Sea divide for Israel?',volume:'962K',thumb:'sea',outcomes:[['Yes',.95],['No',.05]],rule:'Resolves from Exodus 14:21–22.'},
  {id:'elijah',type:'binary',category:'Prophets',sub:'1 Kings',reference:'1 Kings 18:36–38',title:'Will fire consume Elijah’s offering?',volume:'542K',thumb:'fire',outcomes:[['Yes',.93],['No',.07]],rule:'Resolves from 1 Kings 18:36–38.'},
  {id:'peter-water',type:'binary',category:'Miracles',sub:'Matthew',reference:'Matthew 14:28–29',title:'Will Peter step out and walk toward Jesus?',volume:'411K',thumb:'water',outcomes:[['Yes',.88],['No',.12]],rule:'Resolves from Matthew 14:28–29.'},
  {id:'jonah',type:'multi',category:'Prophets',sub:'Jonah',reference:'Jonah 1:1–3',title:'Where does Jonah go after God tells him to go to Nineveh?',volume:'318K',thumb:'ship',outcomes:[['Tarshish',.91],['Nineveh',.09]],rule:'Resolves from Jonah 1:1–3.'},
  {id:'samaritan',type:'multi',category:'Parables',sub:'Luke',reference:'Luke 10:30–37',title:'Who stops to help the wounded man?',volume:'250K',thumb:'road',outcomes:[['A Samaritan',.93],['A priest',.04]],rule:'Resolves from Luke 10:30–37.'}
];

const featured = ['david-goliath','red-sea','paul-rome'];
const topics = ['All','Jesus','David','Moses','Paul','Peter','Genesis','Gospels','Miracles','Prophecy','Resurrection','Kings','Parables','Acts'];
const navTopics = ['Trending','Combos','Perps','Breaking','New','Gospels','History','Torah','Prophets','Acts','Letters','Miracles','Parables','Revelation'];

const state = {
  route: parseRoute(location.hash), query:'', topic:'All', featuredIndex:0,
  ticket:{marketId:'david-goliath', outcomeIndex:0, amount:0, tab:'predict'},
  eventTab:'comments', mobileTicket:false,
  balance:Number(localStorage.getItem('hm_balance')||2450),
  predictions:JSON.parse(localStorage.getItem('hm_predictions')||'{}'),
  scripture:{}, livePercent:51
};

function parseRoute(hash){
  const h=(hash||'#/').replace(/^#/,'');
  if(h.startsWith('/markets')) return {name:'markets'};
  if(h.startsWith('/event/')) return {name:'event',id:decodeURIComponent(h.split('/')[2]||'david-goliath')};
  return {name:'home'};
}
function market(id){return markets.find(m=>m.id===id)||markets[0]}
function pct(v){return `${Math.round(v*100)}%`}
function cents(v){return `${Math.round(v*100)}¢`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function save(){localStorage.setItem('hm_balance',String(state.balance));localStorage.setItem('hm_predictions',JSON.stringify(state.predictions))}

const icon = name => {
  const d={search:'<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.6 2.1c-1 .6-1.4 1.1-1.4 2.1"/><path d="M12 17h.01"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',trend:'<path d="M3 16l5-5 4 3 7-8"/><path d="M14 6h5v5"/>',bookmark:'<path d="M6 4.5A1.5 1.5 0 0 1 7.5 3h9A1.5 1.5 0 0 1 18 4.5V21l-6-4-6 4V4.5Z"/>',sliders:'<path d="M4 6h8M16 6h4M4 12h4M12 12h8M4 18h12M20 18h0"/><circle cx="14" cy="6" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="18" cy="18" r="2"/>',link:'<path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1 1"/><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1-1"/>',code:'<path d="m9 18-6-6 6-6M15 6l6 6-6 6"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 4 3 14 0 18M12 3c-3 4-3 14 0 18"/>',gift:'<path d="M4 10h16v11H4zM2.5 7h19v4h-19zM12 7v14"/>',chev:'<path d="m9 18 6-6-6-6"/>'};
  return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${d[name]||''}</svg>`;
};
function logo(){return `<svg class="logo-mark" viewBox="0 0 34 34" aria-hidden="true"><path d="M3 8.5 17 3v28L3 25.5z"/><path d="M17 3 31 8.5v17L17 31"/><path d="M8 11.5 17 8v18l-9-3.5z"/></svg>`}
function thumb(key,small=false){const map={david:['#65411f','#dc9c4e','D'],lazarus:['#1a6b61','#75c2ae','L'],tomb:['#244b6d','#e5e2bd','✦'],walls:['#5d4b39','#ae9475','J'],samson:['#57305c','#c779c6','S'],paul:['#275969','#7bb1bf','P'],mountain:['#5d5545','#c6b78e','A'],sea:['#125c75','#56bad5','≈'],fire:['#7b301f','#ef8934','F'],water:['#245d78','#77c5db','W'],ship:['#425d69','#acc8d2','J'],road:['#6a563a','#cfb27d','S']};const [a,b,t]=map[key]||['#3b4650','#75828b','✦'];return `<span class="thumb ${small?'small':''}" style="--a:${a};--b:${b}">${t}</span>`}

function header(active){
  return `<header class="site-header"><div class="topbar shell"><a class="brand" href="#/">${logo()}<span>HolyMarket</span></a><label class="global-search">${icon('search')}<input id="global-search" placeholder="Search HolyMarket..." value="${esc(state.query)}"><kbd>/</kbd></label><a class="primary-cta" href="#/markets">Explore Scripture ↗</a><button class="header-icon" aria-label="Help">${icon('help')}</button><button class="header-icon" aria-label="Menu">${icon('menu')}</button></div><nav class="nav"><div class="nav-scroll shell">${navTopics.map((n,i)=>`<a class="nav-item ${i===0&&active==='home'?'active':''}" href="#/markets">${i===0?icon('trend'):''}${n}</a>${i===4?'<i class="nav-divider"></i>':''}`).join('')}<span class="nav-end">›</span></div></nav></header>`;
}
function notice(){return `<div class="notice">${icon('globe')}<span>HolyMarket uses virtual Talents. Predict first, then reveal the Scripture.</span><u>Learn more ↗</u></div>`}

function featuredChart(m){return `<div class="feature-chart"><div class="legend"><span><i></i>${esc(m.outcomes[0][0])} ${pct(m.outcomes[0][1])}</span><span><i class="b"></i>${esc(m.outcomes[1][0])} ${pct(m.outcomes[1][1])}</span></div><svg viewBox="0 0 450 245" preserveAspectRatio="none"><g class="grid"><line x1="0" y1="30" x2="420" y2="30"/><line x1="0" y1="86" x2="420" y2="86"/><line x1="0" y1="142" x2="420" y2="142"/><line x1="0" y1="198" x2="420" y2="198"/></g><path class="chart-line one" d="M12 140 L40 128 L68 135 L94 96 L124 105 L153 73 L184 82 L216 62 L246 72 L279 67 L312 89 L344 72 L376 79 L408 58"/><path class="chart-line two" d="M12 190 L45 184 L80 170 L112 176 L145 160 L178 165 L212 155 L244 163 L280 150 L313 158 L347 147 L380 152 L408 144"/><circle class="dot blue" cx="408" cy="58" r="5"/><circle class="dot gray" cx="408" cy="144" r="5"/></svg><div class="axis"><span>80%</span><span>60%</span><span>40%</span><span>20%</span><span>0%</span></div><div class="bursts"><span>+ ◈6</span><span>+ ◈4</span><span>+ ◈124</span><span>+ ◈1,963</span></div></div>`}
function featureCard(m){return `<section class="featured" data-action="open-market" data-market="${m.id}"><div class="feature-left"><div class="feature-head">${thumb(m.thumb)}<div><small>${esc(m.category)} · ${esc(m.sub)}</small><h1>${esc(m.title)}</h1></div><span class="feature-actions">${icon('link')}${icon('bookmark')}</span></div><div class="feature-outcomes">${m.outcomes.map(o=>`<div><span>${esc(o[0])}</span><strong>${pct(o[1])}</strong></div>`).join('')}<div><span>Other</span><strong>&lt;1%</strong></div><div><span>Other outcome</span><strong>&lt;1%</strong></div></div><div class="feature-comments"><p><i></i><span><b>BereanReader</b> Read the passage after you lock your pick.</span></p><p><i class="alt"></i><span><b>ScriptureDaily</b> The resolution source is Scripture.</span></p></div><div class="feature-vol">◈${m.volume} Vol.</div></div><div class="feature-right">${featuredChart(m)}<div class="chart-footer"><span>⇄ Monthly</span><span>◁ HolyMarket</span></div></div></section>`}
function discovery(){const news=[['Will Jesus calm the storm?','95%','↗ 77%'],['Will Jonah go directly to Nineveh?','12%','↘ 65%'],['Will Peter deny Jesus three times?','93%','↗ 20%']];const hot=[['David','◈942K today'],['Paul','◈3M today'],['Moses','◈4M today'],['Peter','◈4M today'],['Jonah','◈16.1K today']];return `<aside class="discovery"><h2>Breaking News ›</h2>${news.map((n,i)=>`<div class="news"><span>${i+1}</span><p>${n[0]}</p><div><b>${n[1]}</b><small class="${n[2].includes('↘')?'down':''}">${n[2]}</small></div></div>`).join('')}<hr><h2>Hot topics ›</h2>${hot.map((h,i)=>`<div class="hot"><span>${i+1}</span><b>${h[0]}</b><small>${h[1]} ♦</small><em>›</em></div>`).join('')}<a class="explore" href="#/markets">Explore all</a></aside>`}
function renderHome(){const m=market(featured[state.featuredIndex]);return `${header('home')}${notice()}<main class="home shell"><div class="hero-grid">${featureCard(m)}${discovery()}</div><div class="carousel"><div class="dots"><i></i>${featured.map((_,i)=>`<button class="${i===state.featuredIndex?'active':''}" data-action="carousel" data-index="${i}"></button>`).join('')}</div><div><a href="#/markets">‹ Gospels</a><a href="#/markets">History ›</a></div></div><section class="home-all"><div class="section-title"><h2>All markets</h2><a href="#/markets">Explore all ›</a></div><div class="preview-grid">${markets.slice(0,3).map(renderCard).join('')}</div></section></main>`}

function outcomeRow(m,o,i){return `<div class="outcome-row"><span>${esc(o[0])}</span><strong>${pct(o[1])}</strong><button class="yes" data-action="open-market" data-market="${m.id}" data-outcome="${i}">Yes</button><button class="no" data-action="open-market" data-market="${m.id}" data-outcome="${i}">No</button></div>`}
function multiCard(m){return `<article class="market-card" data-action="open-market" data-market="${m.id}"><div class="card-head">${thumb(m.thumb)}<h3 class="market-title">${esc(m.title)}</h3></div><div>${m.outcomes.slice(0,2).map((o,i)=>outcomeRow(m,o,i)).join('')}</div><footer><span>${m.volume} Vol.</span><em>⇄</em><i></i>${icon('gift')}${icon('bookmark')}</footer></article>`}
function binaryCard(m){const o=m.outcomes[0];return `<article class="market-card" data-action="open-market" data-market="${m.id}"><div class="card-head">${thumb(m.thumb)}<h3 class="market-title">${esc(m.title)}</h3></div><div class="binary-row"><span>${esc(m.reference.split(':')[0])}</span><strong>${pct(o[1])}</strong><button class="yes" data-action="open-market" data-market="${m.id}" data-outcome="0">Yes</button><button class="no" data-action="open-market" data-market="${m.id}" data-outcome="1">No</button></div><footer><span>${m.volume} Vol.</span><i></i>${icon('gift')}${icon('bookmark')}</footer></article>`}
function liveCard(m){return `<article class="market-card live-card" data-action="open-market" data-market="${m.id}"><div class="live-head">${thumb(m.thumb)}<h3 class="market-title">${esc(m.title)}</h3><div class="gauge"><svg viewBox="0 0 70 42"><path d="M6 36a29 29 0 0 1 58 0"/><path class="progress" d="M6 36a29 29 0 0 1 58 0"/></svg><b>${state.livePercent}%</b><small>Up</small></div></div><div class="live-money"><span>+ ◈5</span><span>+ ◈49</span><span>+ ◈15</span><span>+ ◈186</span></div><div class="updown"><button class="up" data-action="open-market" data-market="${m.id}" data-outcome="0">Up</button><button class="down" data-action="open-market" data-market="${m.id}" data-outcome="1">Down</button></div><footer><span class="live-meta"><b></b>LIVE · ${esc(m.category)}</span><i></i>${icon('bookmark')}</footer></article>`}
function matchupCard(m){return `<article class="market-card" data-action="open-market" data-market="${m.id}">${m.teams.map((t,i)=>`<div class="team-row">${thumb(i? 'samson':m.thumb,true)}<span>${t[1]}</span><b>${esc(t[0])}</b><strong>${pct(t[2])}</strong></div>`).join('')}<div class="team-buttons"><button data-action="open-market" data-market="${m.id}" data-outcome="0">${esc(m.teams[0][0])}</button><button data-action="open-market" data-market="${m.id}" data-outcome="1">${esc(m.teams[1][0])}</button></div><footer><span class="game"><b></b>${m.stage}</span><span>${m.volume} Vol.</span><span>· ${esc(m.sub)}</span><i></i>${icon('bookmark')}</footer></article>`}
function renderCard(m){return m.type==='live'?liveCard(m):m.type==='matchup'?matchupCard(m):m.type==='binary'?binaryCard(m):multiCard(m)}

function filteredMarkets(){const q=state.query.trim().toLowerCase();return markets.filter(m=>{const hay=`${m.title} ${m.category} ${m.sub} ${m.reference}`.toLowerCase();const topic=state.topic==='All'||hay.includes(state.topic.toLowerCase());return topic&&(!q||hay.includes(q))})}
function renderMarkets(){return `${header('markets')}<main class="markets shell"><div class="markets-heading"><h1>All markets</h1><div><button data-action="focus-market-search">${icon('search')}</button><button>${icon('sliders')}</button><button>${icon('bookmark')}</button></div></div><div class="topic-rail">${topics.map(t=>`<button class="${state.topic===t?'active':''}" data-action="topic" data-topic="${esc(t)}">${esc(t)}</button>`).join('')}<span>›</span></div><div class="filterbar"><label>${icon('search')}<input id="market-search" placeholder="Search" value="${esc(state.query)}"></label><button>24hr Volume⌄</button><button class="active">All</button><button>Active</button><label><input type="checkbox">Hide sports</label><label><input type="checkbox">Hide crypto</label><label><input type="checkbox">Hide earnings</label></div><div class="market-grid">${filteredMarkets().map(renderCard).join('')}</div>${filteredMarkets().length?'':'<p class="empty">No Scripture markets found.</p>'}<section class="faq"><h2>Frequently Asked Questions</h2>${[['What is HolyMarket?','A virtual-only Scripture prediction learning concept.'],['How do HolyMarket odds work?','Percentages represent community picks using virtual Talents.'],['How are markets resolved?','Every market cites the Scripture passage used to resolve it.']].map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</section></main>`}

function eventChart(m){const a=m.outcomes[0],b=m.outcomes[1];return `<div class="event-chart"><svg viewBox="0 0 610 255" preserveAspectRatio="none"><g class="grid"><line x1="0" y1="24" x2="566" y2="24"/><line x1="0" y1="86" x2="566" y2="86"/><line x1="0" y1="148" x2="566" y2="148"/><line x1="0" y1="210" x2="566" y2="210"/></g><path class="event-line one" d="M32 145 L72 126 L108 130 L142 112 L174 118 L207 100 L246 108 L283 94 L320 102 L357 91 L402 89 L445 80 L482 79 L525 70"/><path class="event-line two" d="M32 210 L90 209 L150 210 L210 208 L270 210 L330 209 L390 210 L450 208 L525 209"/><circle cx="525" cy="70" r="5" class="event-dot blue"/><circle cx="525" cy="209" r="5" class="event-dot gray"/></svg><div class="event-axis"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div class="time">9:00 AM</div><div class="event-label a"><i></i><span>${esc(a[0])}</span><b>${pct(a[1])}</b></div><div class="event-label b"><i></i><span>${esc(b[0])}</span><b>${pct(b[1])}</b></div></div>`}
function scoreboard(m){const teams=m.teams||[[m.outcomes[0][0],13,m.outcomes[0][1]],[m.outcomes[1][0],5,m.outcomes[1][1]]];const scores=m.scores||[['13','12'],['5','11']];return `<div class="scoreboard"><div class="score-head"><span></span><span></span><span>M1</span><span class="hot">M2</span><span>M3</span><span>ODDS</span></div>${teams.map((t,i)=>`<div class="score-line">${thumb(i? 'samson':m.thumb,true)}<b>${esc(t[0])}</b><span>${scores[i][0]}</span><span>${scores[i][1]}</span><span>–</span><strong>${pct(t[2])}</strong></div>`).join('')}</div>`}
function ticket(m){const idx=Math.min(state.ticket.outcomeIndex,m.outcomes.length-1);const selected=m.outcomes[idx];return `<div class="combo"><span>◫</span><b>Build a combo</b></div><div class="ticket"><div class="ticket-market">${thumb(m.thumb,true)}<div><small>${esc(m.title)}</small><strong>${esc(selected[0])}</strong></div></div><div class="ticket-tabs"><button class="${state.ticket.tab==='predict'?'active':''}" data-action="ticket-tab" data-tab="predict">Predict</button><button class="${state.ticket.tab==='review'?'active':''}" data-action="ticket-tab" data-tab="review">Review</button><span>Market⌄</span></div>${state.ticket.tab==='predict'?`<div class="ticket-outcomes"><button class="${idx===0?'active':''}" data-action="ticket-outcome" data-index="0">${esc(m.outcomes[0][0])} ${cents(m.outcomes[0][1])}</button><button class="${idx===1?'active':''}" data-action="ticket-outcome" data-index="1">${esc(m.outcomes[1][0])} ${cents(m.outcomes[1][1])}</button></div><div class="amount"><label>Amount</label><div><span>◈</span><input id="amount-input" inputmode="numeric" type="number" min="0" value="${state.ticket.amount||''}" placeholder="0"></div></div><div class="quick">${[1,5,10,100].map(n=>`<button data-action="quick-add" data-value="${n}">+◈${n}</button>`).join('')}</div>`:`<div class="review"><div><span>Outcome</span><b>${esc(selected[0])}</b></div><div><span>Stake</span><b>◈${state.ticket.amount}</b></div><div><span>Reference</span><b>${esc(m.reference)}</b></div></div>`}<button class="predict-button" data-action="lock-prediction">${state.predictions[m.id]?'Prediction locked':'Predict'}</button></div>`}
function renderEventTab(m){if(state.eventTab==='comments')return `<div class="tab-content"><div class="comment-item"><i></i><div><b>HolyMarket</b><p>Lock a prediction, then compare your pick with the cited passage.</p></div></div><div class="comment-item"><i class="alt"></i><div><b>BereanReader</b><p>The resolution source is clearly cited.</p></div></div></div>`;if(state.eventTab==='activity')return `<div class="tab-content activity"><div><span>ShepherdKing</span><b>Placed a virtual prediction</b><small>◈25 · just now</small></div><div><span>ScriptureDaily</span><b>Viewed this market</b><small>3m</small></div></div>`;if(state.eventTab==='rules')return `<div class="tab-content rules"><h3>Rules</h3><p>${esc(m.rule)}</p><div class="facts"><div><small>Volume</small><b>◈ ${m.volume}</b></div><div><small>Status</small><b>Active</b></div><div><small>Resolution source</small><b>${esc(m.reference)}</b></div><div><small>Points</small><b>Virtual only</b></div></div></div>`;const s=state.scripture[m.id];if(!state.predictions[m.id])return `<div class="tab-content locked"><b>Scripture stays hidden until you predict.</b><p>Lock a virtual prediction to reveal ${esc(m.reference)}.</p></div>`;if(!s||s.status==='loading')return `<div class="tab-content loading"><span></span><span></span><span></span></div>`;return `<div class="tab-content scripture"><div><b>${esc(s.data.reference||m.reference)}</b><small>${esc(s.data.version_title||'Bible')}</small></div><p>${esc(s.data.content||'')}</p><small>${esc(s.data.attribution||s.data.copyright||'')}</small></div>`}
function renderEvent(m){return `${header('event')}${notice()}<main class="event shell"><section class="event-main"><div class="breadcrumb">${esc(m.category)} · ${esc(m.sub)} · ${esc(m.reference.split(':')[0])}</div><div class="event-heading"><h1>${esc(m.title)}</h1><div>${icon('sliders')}${icon('code')}${icon('bookmark')}${icon('link')}</div></div><div class="event-meta"><span>● ${m.stage||'Story 2 of 3'}</span><em>${m.volume} Vol.</em></div>${scoreboard(m)}${eventChart(m)}<div class="event-tabs">${['comments','activity','scripture','rules'].map(t=>`<button class="${state.eventTab===t?'active':''}" data-action="event-tab" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>${renderEventTab(m)}</section><aside class="ticket-side">${ticket(m)}</aside></main><button class="mobile-predict" data-action="mobile-ticket">Predict</button><div class="mobile-sheet-wrap ${state.mobileTicket?'open':''}"><div class="backdrop" data-action="close-mobile"></div><div class="mobile-sheet"><button class="sheet-close" data-action="close-mobile">×</button>${ticket(m)}</div></div>`}

function render(){state.route=parseRoute(location.hash);if(state.route.name==='markets')app.innerHTML=renderMarkets();else if(state.route.name==='event'){const m=market(state.route.id);state.ticket.marketId=m.id;app.innerHTML=renderEvent(m)}else app.innerHTML=renderHome()}
function openMarket(id,index=0){state.ticket.marketId=id;state.ticket.outcomeIndex=Number(index)||0;state.ticket.amount=0;state.ticket.tab='predict';state.eventTab='comments';location.hash=`#/event/${encodeURIComponent(id)}`}
function setTicketOutcome(index){state.ticket.outcomeIndex=Number(index)||0;render()}
function quickAdd(amount){state.ticket.amount=Math.min(state.balance,state.ticket.amount+Number(amount||0));render()}
async function loadScripture(m){state.scripture[m.id]={status:'loading'};render();try{let data;try{const r=await fetch(`/api/scripture?ref=${encodeURIComponent(m.reference)}`);if(r.ok)data=await r.json()}catch{}if(!data){const r=await fetch(`https://bible-api.com/${encodeURIComponent(m.reference)}?translation=web`);if(r.ok){const d=await r.json();data={reference:d.reference||m.reference,content:d.text||'',version_title:'World English Bible',attribution:'World English Bible — public domain'}}}if(!data)throw new Error();state.scripture[m.id]={status:'ready',data}}catch{state.scripture[m.id]={status:'ready',data:{reference:m.reference,content:'Open the cited passage to see how Scripture resolves this market.',version_title:'Scripture'}}}render()}
function lockPrediction(){const m=market(state.ticket.marketId);if(state.predictions[m.id])return;const amount=Math.max(0,Math.min(state.balance,Number(state.ticket.amount)||0));state.predictions[m.id]={outcomeIndex:state.ticket.outcomeIndex,amount};state.balance-=amount;save();state.eventTab='scripture';loadScripture(m)}

app.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(a==='open-market'){e.stopPropagation();openMarket(el.dataset.market,el.dataset.outcome)}else if(a==='carousel'){state.featuredIndex=Number(el.dataset.index)||0;render()}else if(a==='topic'){state.topic=el.dataset.topic;render()}else if(a==='focus-market-search'){document.querySelector('#market-search')?.focus()}else if(a==='ticket-outcome')setTicketOutcome(el.dataset.index);else if(a==='quick-add')quickAdd(el.dataset.value);else if(a==='ticket-tab'){state.ticket.tab=el.dataset.tab;render()}else if(a==='event-tab'){state.eventTab=el.dataset.tab;render()}else if(a==='lock-prediction')lockPrediction();else if(a==='mobile-ticket'){state.mobileTicket=true;render()}else if(a==='close-mobile'){state.mobileTicket=false;render()}});
app.addEventListener('input',e=>{if(e.target.id==='market-search'){state.query=e.target.value;render();queueMicrotask(()=>{const x=document.querySelector('#market-search');if(x){x.focus();x.setSelectionRange(state.query.length,state.query.length)}})}else if(e.target.id==='amount-input')state.ticket.amount=Math.max(0,Number(e.target.value)||0)});
app.addEventListener('keydown',e=>{if(e.target.id==='global-search'&&e.key==='Enter'){state.query=e.target.value;location.hash='#/markets'}});
window.addEventListener('hashchange',render);
window.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName||'')){e.preventDefault();document.querySelector('#global-search')?.focus()}});
setInterval(()=>{state.livePercent=48+Math.floor(Math.random()*8);const n=document.querySelector('.gauge b');if(n)n.textContent=`${state.livePercent}%`},3000);
render();
